# Generated by Django 4.1.3 on 2022-11-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('tg_id', models.BigIntegerField(default=0, verbose_name='Telegram ID')),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('language', models.CharField(choices=[('oz', "O'zbek"), ('uz', 'Узбек'), ('ru', 'Руский'), ('en', 'Ingliz')], max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('0', "Botni o'chirgan"), ('1', 'Faol'), ('2', "O'chirib qaytgan")], default='1', max_length=10)),
                ('amount', models.IntegerField(default=0)),
                ('step', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
    ]
