# Generated by Django 4.1.3 on 2022-11-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_starttext'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.TextField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
