# Generated by Django 4.1.3 on 2022-11-26 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='faq',
        ),
    ]
