# Generated by Django 4.1.3 on 2022-12-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_about_name_ru_about_text_ru_contactinfo_contact_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oz', models.JSONField(default=dict, verbose_name="O'zbek")),
                ('ru', models.JSONField(default=dict, verbose_name='Руский')),
            ],
            options={
                'verbose_name': "So'z",
                'verbose_name_plural': "So'zlar",
            },
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='contact',
            field=models.TextField(max_length=512, verbose_name="Aloqa ma'lumotlari o'zbek"),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='contact_ru',
            field=models.TextField(max_length=512, null=True, verbose_name="Aloqa ma'lumotlari rus"),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(max_length=1024, null=True, verbose_name="Kurs haqida ma'lumot o'zbek"),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description_ru',
            field=models.TextField(max_length=1024, null=True, verbose_name="Kurs haqida ma'lumot rus"),
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(max_length=32, verbose_name="Nomi o'zbek"),
        ),
        migrations.AlterField(
            model_name='courses',
            name='name_ru',
            field=models.CharField(max_length=32, null=True, verbose_name='Nomi rus'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='faq',
            field=models.TextField(max_length=4096, verbose_name="Ko'p beriladigan savollar o'zbek"),
        ),
        migrations.AlterField(
            model_name='faq',
            name='faq_ru',
            field=models.TextField(max_length=4096, null=True, verbose_name="Ko'p beriladigan savollar rus"),
        ),
        migrations.AlterField(
            model_name='starttext',
            name='text',
            field=models.TextField(max_length=1024, verbose_name="Start matni o'zbek"),
        ),
        migrations.AlterField(
            model_name='starttext',
            name='text_ru',
            field=models.TextField(max_length=1024, null=True, verbose_name='Start matni rus'),
        ),
    ]
