# Generated by Django 4.1.3 on 2022-12-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_language_alter_contactinfo_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='telegram_group',
            field=models.URLField(max_length=256, null=True, verbose_name='Telegram guruhi demo dars uchun'),
        ),
    ]
