# Generated by Django 4.1.3 on 2022-11-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='message_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
