# Generated by Django 4.1.3 on 2022-11-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_messages_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='answer',
            field=models.TextField(null=True),
        ),
    ]
