# Generated by Django 4.1.3 on 2022-11-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_messages_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_answer',
            field=models.BooleanField(default=False),
        ),
    ]
