# Generated by Django 4.1.3 on 2022-12-01 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_remove_contactinfo_faq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0006_messages_is_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='Ismi')),
                ('sex', models.CharField(choices=[('man', 'Erkak'), ('woman', 'Ayol')], max_length=10, null=True, verbose_name='Jinsi')),
                ('address', models.TextField(max_length=255, null=True, verbose_name='Manzil')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Telefon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqti')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.courses', verbose_name='Kurs')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Kusrga yozilgan',
                'verbose_name_plural': 'Kusrga yozilganlar',
            },
        ),
    ]
