# Generated by Django 4.1.3 on 2022-12-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
