# Generated by Django 4.1.3 on 2022-12-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_messages_options_alter_settings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='status',
            field=models.BooleanField(choices=[(True, "To'liq ro'yxatdan o'tgan"), (False, "To'liq ro'yxatdan o'tgmagan")], default=False, verbose_name='Holati'),
        ),
    ]
